services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teddy_db
    volumes:
      - teddy_db:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

  # api:
  #   image: node:18-alpine
  #   container_name: teddy-api
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: sh -c "npm install && npm run start:dev"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #     - redis

volumes:
  teddy_db:
